# Global Variables
CONFIG_PROFILE = "DEFAULT"
NAMESPACE = "axbpjkug04ct"
BUCKET_NAME = "target-bucket"
OBJECT_NAME = "testdirectory/part-00000-a2676ae3-39e8-420f-a7fe-e0843e9fea0e-c000.json"
COMPARTMENT_ID = "ocid1.compartment.oc1..aaaaaaaalnzl6zjv5aarhl32amczyeqwl7ahxnzqxwjpzppb74e7ubouzn4a"
SESSION_ID = "abc123"
user="ocid1.user.oc1..aaaaaaaawxbz5prkm6y3ja5ambupqdfgqn6ggp5zbzojpq7pirvbyqas6dgq"
fingerprint="e4:64:6a:9e:1a:fa:0d:2f:7a:f8:36:d8:8a:18:83:fd"
key_file="krishna.sahu@techment.com_2024-04-24T10_13_19.206Z.pem"
tenancy="ocid1.tenancy.oc1..aaaaaaaauevhkihjbrur3awjyepvnvkelbtw5qss6cjuxhwop4etveapxoja"
region="us-chicago-1"
